spring:
  datasource:
    url: jdbc:mysql://localhost:3306/counter?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 6000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    jdbc-type-for-null: 'null'

server:
  port: 8090

#radis缓存过期时间
cacheexpire:
  captcha: 100
  account: 3600
  order: 36000

#机器位置
counter:
  id: 1000
  #机房ID
  dataCenterId: 0
  #机柜ID
  workerId: 0

logging:
  config: classpath:log4j2.xml
